### PR TITLE
Adding shiny app

### LINKED ISSUE #11: Adding shiny app
Should I create a new repo for shiny app or add it here?

### PR DESCRIPTION
**Pull request by romatik**
Closes #11

### CODE REVIEW

**Comment by vecna** [comment]
Thanks, I'll try today, considering I never used an R script :)

**Comment by berli0z** [comment]
Hello romatik and thanks a lot for your contribution!
I tried the shiny app and i noticed that the dataset included has fields that a regular summary doesn't have, such as concatenatedText, which is texts divided by ; instead of as list, images.count, and concatLanguage

it would be nice if these details are added to the documentation! i don't have the dataset you used during the datathon (it's not public), and i wasnt able to make any visualization on the go with the synthetic dataset i created. hope i get something by the end of the day!
thanks again, i'm pretty sure claudio will let you know soon

**Comment by romatik** [comment]
@vecna, can you give the link to the dataset introduction you had for the hackathon? It was something like bit.ly/dssg-2019-something. It had the definitions for the dataset.

@berli0z, I've deliberately deleted the datasets since they are quite big to upload and also we are not supposed to share them anyway. I can record short screen-capture with how this app works on my machine as documentation. Would that be enough? Or what exactly do you want to achieve in the end with this? My take on this was mostly to have it as a template for future work since it can't be used in "production" anyway.

**Comment by berli0z** [comment]
@romatik  Good thing indeed you didn't include the datasets! There is no "production" planned for this repository, but everything that is being added here should be reusable by researchers or other individuals in their own machine :)

I think it would be possible to reuse your code in the future with the data that can be pulled from the summary API: the problem is that three fields are missing and i'm not completely sure of the format they had: that is, "concatenatedText", "images.count" and "concatLanguage".

If eda.R is not able to transform the dataset to include those fields, it would still be nice to have it documented in the readme, or just here in the issue. That's all! To me, we can accept your pull request already :)

**Comment by vecna** [comment]
(apologies for the delay, I had a series of issues)

**Comment by vecna** [comment]
Thanks, we add this doc in regards https://github.com/tracking-exposed/dashboard/wiki/Installing-R-and-shinyapp

**Pull request merged**
